volumes:
  pgdata:
  galaxy-data:

services:
  backend:
    hostname: backend-${TARGET_ENV}
    image: ${REGISTRY_PREFIX}/molevolvr-backend:${IMAGE_TAG}
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
      args:
        - PRIOR_LAYER=backend-base
      cache_from:
        - type=registry,ref=${REGISTRY_PREFIX}/molevolvr-backend:${IMAGE_TAG}
      cache_to:
        - type=inline,ref=${REGISTRY_PREFIX}/molevolvr-backend:${IMAGE_TAG},mode=max
    env_file:
      - .env
    environment:
      - API_PORT=9050
      - "POSTGRES_HOST=db"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    hostname: frontend-${TARGET_ENV}
    image: ${REGISTRY_PREFIX}/molevolvr-frontend:${IMAGE_TAG}
    build:
      context: ./frontend
      cache_from:
        - type=registry,ref=${REGISTRY_PREFIX}/molevolvr-frontend:${IMAGE_TAG}
      cache_to:
        - type=inline,ref=${REGISTRY_PREFIX}/molevolvr-frontend:${IMAGE_TAG},mode=max
    depends_on:
      - backend

  db:
    hostname: ${POSTGRES_HOST}
    # image: postgres:16
    build: ./services/postgres/
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-exports/:/db-exports/
    healthcheck:
      # test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      # interval: 30s
      # timeout: 60s
      # retries: 5
      # start_period: 80s
      test: ["CMD-SHELL", "/opt/healthcheck.sh || exit 1"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 2m

  galaxy:
    image: bgruening/galaxy-stable:latest
    hostname: galaxy-${TARGET_ENV}
    restart: unless-stopped
    ports:
      - "8092:80"            # Galaxy UI available on http://localhost:8092
    volumes:
      - galaxy-data:/export  # Persistent Galaxy database, configs, tools, histories
    env_file:
      - .env
    environment:
      # Disable the first-use wizard for easier deployment
      GALAXY_CONFIG_ALLOW_USER_DELETION: "true"
      GALAXY_CONFIG_ADMIN_USERS: "admin@example.com"
      # Optional: expose Galaxyâ€™s FTP directory (useful for large uploads)
      GALAXY_CONFIG_FTP_UPLOAD_DIR: "/export/ftp"
      # Optional: configure database connection (default is SQLite)
      GALAXY_CONFIG_DATABASE_CONNECTION: >-
        postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/galaxy
    # Optional: increase memory for Pulsar/job runners if needed
    # deploy:
    #   resources:
    #     limits:
    #       memory: 8G
